version: "2"

services:
  rabbitmq:
    image: rabbitmq:3.6.9-management
    ports:
      - 15672:5672
  ruby-invoices:
    build: ./ruby-invoices
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
  proxy-api:
    build: ./proxy-api
    environment:
      - PORT=4000
      - SECRET_KEY_BASE
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - 14000:4000

